events {
    worker_connections 1024;
}

http {
    # Definir el grupo de servidores backend
    upstream backend {
        # Round Robin es el algoritmo por defecto
        server server1:80;
        server server2:80;
    }

    # Servidor del balanceador de carga
    server {
        listen 80;

        location / {
            proxy_pass http://backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }
}